### ISSUE TITLE
Flutter migration: Android service integration

### ISSUE THREAD

**Issue by Izchomatik** [roc-streaming/roc-droid#98]
roc-droid Flutter migration child issue.

Add GUI model connection to backend services.

- [x] Move required android services to android/.../service - ?
- [x] Add Connector (android/.../connector)
- [x] Add Agent (lib/src/agent)
- [x] Add Platform Channels
- [x] Check functionality
- [x] Read backend state on startup
- [x] Add documentation

**Comment by gavv** [comment]
Results of testing latest branch from #123.

### Problem 1

I was getting this error when starting receiver:

```
00:26:01.684 [11020:11020]  I  [rocdroid.AndroidConnectorImpl] Requesting POST_NOTIFICATIONS permission
00:26:01.686 [11020:11020]  D  [rocdroid.MainActivity] Requesting permission directly
00:26:01.852 [11020:11020]  D  [CompatibilityChangeReporter] Compat change id reported: 78294732; UID 10868; state: DISABLED
00:26:01.852 [11020:11020]  W  [rocdroid.MainActivity] Permission is rejected
00:26:01.852 [11020:11020]  W  [rocdroid.AndroidConnectorImpl] Permission request failed
00:26:01.853 [11020:11020]  I  [rocdroid.MainActivity] Resuming main activity
```

I opened Settings -> Apps -> Roc Droid -> Notifications and saw that notifiations are "Blocked" for some reason. (Though they were working right before I upgraded to new version).

I've manually allowed notifications in settings and the problem disappeared.

### Problem 2

When starting receiver, each time I get this error:

```
00:30:05.243 [70770:73020]  E  [AndroidRuntime] FATAL EXCEPTION: Thread-5
00:30:05.243 [70770:73020]  E  [AndroidRuntime] Process: org.rocstreaming.rocdroid, PID: 7077
00:30:05.243 [70770:73020]  E  [AndroidRuntime] java.lang.ExceptionInInitializerError
00:30:05.243 [70770:73020]  E  [AndroidRuntime] 	at org.rocstreaming.rocdroid.StreamingService.h(Unknown Source:119)
00:30:05.243 [70770:73020]  E  [AndroidRuntime] 	at L1.j.run(Unknown Source:116)
00:30:05.243 [70770:73020]  E  [AndroidRuntime] 	at java.lang.Thread.run(Thread.java:1012)
00:30:05.243 [70770:73020]  E  [AndroidRuntime] Caused by: java.lang.ClassNotFoundException: org.rocstreaming.roctoolkit.RocLogLevel
00:30:05.243 [70770:73020]  E  [AndroidRuntime] 	at java.lang.Runtime.nativeLoad(Native Method)
00:30:05.243 [70770:73020]  E  [AndroidRuntime] 	at java.lang.Runtime.loadLibrary0(Runtime.java:1079)
00:30:05.243 [70770:73020]  E  [AndroidRuntime] 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
00:30:05.243 [70770:73020]  E  [AndroidRuntime] 	at java.lang.System.loadLibrary(System.java:1765)
00:30:05.243 [70770:73020]  E  [AndroidRuntime] 	at M1.e.a(Unknown Source:21)
00:30:05.243 [70770:73020]  E  [AndroidRuntime] 	at org.rocstreaming.roctoolkit.a.<clinit>(Unknown Source:4)
00:30:05.243 [70770:73020]  E  [AndroidRuntime] 	... 3 more
00:30:05.275 [15570:73070]  W  [ActivityManager] crash : org.rocstreaming.rocdroid,10868
00:30:05.302 [70770:73020]  I  [Process] Sending signal. PID: 7077 SIG: 9
00:30:05.380 [15570:25650]  I  [ActivityManager] Process org.rocstreaming.rocdroid (pid 7077) has died: fg +50 FGS (201,2685)
```

I tried to explicitly enable multidex ([src](https://stackoverflow.com/questions/49886597/multidex-issue-with-flutter)), but it didn't help, maybe I did something wrong.

I switched from release to debug build (`doit launch variant=debug`) and the problem disappeared.

### Problem 3

Now receiver work great except one bug:

* start receiver
* close the app
* playback continues
* tap to notification
* app starts
* in UI, receiver state is stopped, however actually it's started and playing
* start button doesn't work (and hence I can't stop receiver either)
* I can stop receiver via notification, then it becomes possible to start it via UI

**Comment by gavv** [comment]
Problem 1 is probably caused by reinstalling app with adb - needs more testing.

Problem 2 can be fixed by adding:

```
-keep class org.rocstreaming.roctoolkit.** { *; }
```

to `android/app/proguard-rules.pro`.

We can do it for now, but I think the proper fix should be done on roc-java side.

**Comment by Izchomatik** [comment]
> Problem 1 is probably caused by reinstalling app with adb - needs more testing.
> 
> Problem 2 can be fixed by adding:
> 
> ```
> -keep class org.rocstreaming.roctoolkit.** { *; }
> ```
> 
> to `android/app/proguard-rules.pro`.
> 
> We can do it for now, but I think the proper fix should be done on roc-java side.

Problem 2: added suggested line

**Comment by gavv** [comment]
A few more fixes are needed:

### ✅ 1. Startup state

Read android service state at start and propagate to model.
I'll handle this in #131.

### ✅ 2. Backend exceptions

Kotlin may throw exceptions to dart (you can find various `throw FlutterError` calls in kotlin) on various failures like connection lost. We forgot to handle them in dart.

Exception from kotlin has string code and string error message. I think `AndroidBackend` in dart should catch those exceptions, translate to backend-independent type, and re-throw them. It could map string error codes from kotlin to different exception classes, for example. Error text message can be forwarded as is.

Finally, in model we should handle exceptions and show error to user.

### ✅ 3. IsAlive properties

```dart
abstract class Backend {
  abstract bool receiverIsAlive;
  abstract bool senderIsAlive;
```

I just noticed that these two properties are writable from outside (e.g. from model). We should make them read-only in public interface, only backend itself should be able to update them.

### ✅ 4. Capture type

Currently model.Sender hard-codes `AndroidCaptureType.captureApps` when it calls backend, but instead it should forward value set from UI.

### ✅ 5. Async constructors

`_setDefultValues` in sender/receiver is async method, but it's called from ctor without `await`, which creates a race.

Imagine you create sender, it constructor returns, but setDefultValues was not executed yet; then you modify sender state, then setDefultValues is executed and overrides your changes. Another possible bug is that returned sender object may have uninitialized fields because setDefultValues wasn't called yet.

It seems that in model initialization we may need to query backend, which may need calling async functions. I think it makes sense to make creation of all models asynchronous, like it was done in #128.

In #132 I've added linter rule that detects thus bug.

----

@Izchomatik Could you take a look at these problems (except first)?

**Comment by gavv** [comment]
A few more bugs:

### ✅ 6. Handle notification dismissal

When notification is swiped out, we should stop sender/receiver and terminate background service. Otherwise notification is constantly re-appearing, which may be annoying.

### ✅ 7. Missing permission after reinstall

If I have roc droid with all permissions granted, then I uninstall it, and install apk again, by default notification permission is set to "blocked", and roc droid doesn't ask to grant it - i.e. sender/receiver buttons just silently fail.
